### ISSUE TITLE
Attempting to run a PAUP* search without generating nexus crashes

### ISSUE THREAD

**Issue by SimonGreenhill** [marccanby/linguiphyr#5]
I didn't realise I needed to 'generate' a nexus before running PAUP*, this then crashes with:

```r
Warning: Error in file: cannot open the connection
  64: file
  63: scan
  62: ape::read.nexus
  61: read_trees_from_paup
  60: read_and_name_trees_paup
  47: observe
  46: <observer>
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>
```

Steps to replicate:
1. Change to "Trees" tab
2. Click "run PAUP*"

Perhaps the button should not be enabled until "Generate" has been clicked, or clicking "Run PAUP*" should trigger generate if the file does not exist.

**Comment by marccanby** [comment]
You actually shouldn't need to hit the "Generate Nexus" button before hitting "Run PAUP*" – and in fact I have not had this issue. In any case, I just pushed several changes to make the tree search process more smooth (e.g., by making the 'Loading......' modal box remain until search is done, rather than for a fixed time), as well as other related changes.
Would you mind trying again and see if you get this issue? If not, let's close the issue. Thanks!

**Comment by SimonGreenhill** [comment]
great, this looks fixed now (or I can't recreate my original problem)
